spring:
  application:
    name: groupbuy-service
  datasource:
    url: jdbc:postgresql://localhost:5433/groupbuy
    username: groupbuy
    password: groupbuy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
#    serialization:
#      write-dates-as-timestamps: false
  output:
    ansi:
      enabled: always
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8081
