spring.application.name=inventory-service
server.port=8082

# DB
spring.datasource.url=jdbc:postgresql://localhost:5434/inventory
spring.datasource.username=inventory
spring.datasource.password=inventory
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# Kafka
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=inventory-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
