# yaml-language-server: $schema=https://coderabbit.ai/schema.v2.json

language: "ko-KR"

reviews:
  profile: "assertive"
  poem: true
  instructions: |
    all reviews should be technically clear, concise and chill.
  pre_merge_checks:
    docstrings:
      mode: "off"
    title:
      mode: "off"
    description:
      mode: "off"
    issue_assessment:
      mode: "warning"